using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.draw;
using PetrolPumpApp.Models;
using System;
using System.IO;

namespace PetrolPumpApp.Helpers
{
    public class PdfHelper
    {
        public static byte[] GenerateRecordPdf(DispensingRecord record)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                Document document = new Document(PageSize.A4, 50, 50, 25, 25);
                PdfWriter writer = PdfWriter.GetInstance(document, ms);

                document.Open();

                Font headerFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 24, new BaseColor(102, 126, 234));
                Paragraph header = new Paragraph("PETROL PUMP", headerFont);
                header.Alignment = Element.ALIGN_CENTER;
                document.Add(header);

                Font subHeaderFont = FontFactory.GetFont(FontFactory.HELVETICA, 12, BaseColor.GRAY);
                Paragraph subHeader = new Paragraph("Dispensing Record Details", subHeaderFont);
                subHeader.Alignment = Element.ALIGN_CENTER;
                subHeader.SpacingAfter = 30f;
                document.Add(subHeader);

                LineSeparator line = new LineSeparator(1f, 100f, new BaseColor(102, 126, 234), Element.ALIGN_CENTER, -2);
                document.Add(new Chunk(line));
                document.Add(new Paragraph(" "));

                PdfPTable table = new PdfPTable(2);
                table.WidthPercentage = 100;
                table.SpacingBefore = 20f;
                table.SpacingAfter = 20f;
                table.SetWidths(new float[] { 40f, 60f });

                Font labelFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK);
                Font valueFont = FontFactory.GetFont(FontFactory.HELVETICA, 11, new BaseColor(60, 60, 60));

                AddTableRow(table, "Record ID", record.Id.ToString(), labelFont, valueFont);
                AddTableRow(table, "Dispenser Number", record.DispenserNo ?? "N/A", labelFont, valueFont);
                AddTableRow(table, "Quantity Dispensed", record.Volume.ToString("0.00") + " Liters", labelFont, valueFont);
                AddTableRow(table, "Vehicle Number", record.VehicleNumber ?? "N/A", labelFont, valueFont);
                AddTableRow(table, "Payment Mode", record.PaymentMode ?? "N/A", labelFont, valueFont);
                AddTableRow(table, "Transaction Date/Time", record.TransactionDate.ToString("dd/MM/yyyy HH:mm:ss"), labelFont, valueFont);
                AddTableRow(table, "Payment Proof", record.ImagePath != null ? "✓ Uploaded" : "✗ Not Uploaded", labelFont, valueFont);
                AddTableRow(table, "Record Created", record.CreatedAt.ToString("dd/MM/yyyy HH:mm:ss"), labelFont, valueFont);

                document.Add(table);

                document.Add(new Chunk(line));
                document.Add(new Paragraph(" "));

                PdfPTable footerTable = new PdfPTable(2);
                footerTable.WidthPercentage = 100;
                footerTable.SpacingBefore = 30f;

                PdfPCell leftFooter = new PdfPCell(new Phrase("Generated by: Petrol Pump System",
                    FontFactory.GetFont(FontFactory.HELVETICA_OBLIQUE, 9, BaseColor.GRAY)));
                leftFooter.Border = Rectangle.NO_BORDER;
                leftFooter.HorizontalAlignment = Element.ALIGN_LEFT;

                PdfPCell rightFooter = new PdfPCell(new Phrase("Date: " + DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss"),
                    FontFactory.GetFont(FontFactory.HELVETICA_OBLIQUE, 9, BaseColor.GRAY)));
                rightFooter.Border = Rectangle.NO_BORDER;
                rightFooter.HorizontalAlignment = Element.ALIGN_RIGHT;

                footerTable.AddCell(leftFooter);
                footerTable.AddCell(rightFooter);

                document.Add(footerTable);

                Font watermarkFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.LIGHT_GRAY);
                Paragraph watermark = new Paragraph("OFFICIAL RECORD - DO NOT TAMPER", watermarkFont);
                watermark.Alignment = Element.ALIGN_CENTER;
                watermark.SpacingBefore = 20f;
                document.Add(watermark);

                document.Close();
                writer.Close();

                return ms.ToArray();
            }
        }

        private static void AddTableRow(PdfPTable table, string label, string value, Font labelFont, Font valueFont)
        {
            PdfPCell labelCell = new PdfPCell(new Phrase(label, labelFont));
            labelCell.BackgroundColor = new BaseColor(245, 245, 245);
            labelCell.Padding = 10;
            labelCell.PaddingLeft = 15;
            labelCell.Border = Rectangle.NO_BORDER;
            labelCell.BorderWidthBottom = 0.5f;
            labelCell.BorderColorBottom = new BaseColor(220, 220, 220);
            labelCell.VerticalAlignment = Element.ALIGN_MIDDLE;

            PdfPCell valueCell = new PdfPCell(new Phrase(value, valueFont));
            valueCell.BackgroundColor = BaseColor.WHITE;
            valueCell.Padding = 10;
            valueCell.PaddingLeft = 15;
            valueCell.Border = Rectangle.NO_BORDER;
            valueCell.BorderWidthBottom = 0.5f;
            valueCell.BorderColorBottom = new BaseColor(220, 220, 220);
            valueCell.VerticalAlignment = Element.ALIGN_MIDDLE;

            table.AddCell(labelCell);
            table.AddCell(valueCell);
        }
    }
}